CREATE TABLE dbo.users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(200) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
